name: 'Update code'

on:
  pull_request:
    types: [opened, reopened]
jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'translation-platform[bot]' }}
    steps:
      - run: echo "${{ github.event.pull_request.user.login }} created this PR"
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn webpack build --mode=production
      - run: git status