name: 'Update code'

on:
  pull_request:
    types: [opened, reopened]
    branches: 
      - translation-platform/**
jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'ryanwilsonperkin' }}
    steps:
      - run: echo "${{ github.event.pull_request.user.login }} created this PR"
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn webpack build --mode=production
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update generated translation index files
