name: 'Update code'

on:
  push:
    branches:
      - 'translation-platform/**'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.push.pusher.username }} pushed this commit"
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn webpack build --mode=production
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update generated translation index files
